package com.vidya.teacherServices.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import java.sql.Date;
@Entity
@Table(name = "TEACHER_PROFILE")
public class TeacherProfileEntity {
	@Id
    @GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "TEACHER_ID", nullable = false)
    private long TEACHER_ID;
	
	@Column(name = "PROFILE_COMPLETE_FLAG")
	private Integer PROFILE_COMPLETE_FLAG;
	
	@Column(name = "PROFILE_COMPLETE_DATE")
	private Date PROFILE_COMPLETE_DATE;
	
	@Column(name = "REG_SUBJECT_COMPLETE_FLAG")
	private Integer REG_SUBJECT_COMPLETE_FLAG;
	
	@Column(name = "REG_AVAILABILITY_COMPLETE_FLAG")
	private Integer REG_AVAILABILITY_COMPLETE_FLAG;
	
	@Column(name = "REG_BASICINFO1_COMPLETE_FLAG")
	private Integer REG_BASICINFO1_COMPLETE_FLAG;
	
	@Column(name = "REG_BASICEDUCATION_COMPLETE_FLAG")
	private Integer REG_BASICEDUCATION_COMPLETE_FLAG;
	
	@Column(name = "REG_PERSONAL_COMPLETE_FLAG")
	private Integer REG_PERSONAL_COMPLETE_FLAG;
	
	@Column(name = "REG_TERMS1_COMPLETE_FLAG")
	private Integer REG_TERMS1_COMPLETE_FLAG;
	
	@Column(name = "REG_TERMS2_COMPLETE_FLAG")
	private Integer REG_TERMS2_COMPLETE_FLAG;
	
	@Column(name = "REG_CONF_ACK_COMPLETE_FLAG")
	private Integer REG_CONF_ACK_COMPLETE_FLAG;
	
	@Column(name = "BACKGROUD_COMPLETE_FLAG")
	private Integer BACKGROUD_COMPLETE_FLAG;
	
	@Column(name = "BACKGROUD_COMPLETE_DATE")
	private Date BACKGROUD_COMPLETE_DATE;
	
	@Column(name = "CLASS_ID1")
	private String CLASS_ID1;
	
	@Column(name = "CLASS_ID2")
	private String CLASS_ID2;
	
	@Column(name = "CLASS_ID3")
	private String CLASS_ID3;
	
	@Column(name = "CLASS_ALL_FLAG")
	private Integer CLASS_ALL_FLAG;
	
	@Column(name = "SUBJECT_MASTER_ID1")
	private String SUBJECT_MASTER_ID1;
	
	@Column(name = "SUBJECT_MASTER_ID1_PRM_FLAG")
	private Integer SUBJECT_MASTER_ID1_PRM_FLAG;
	
	@Column(name = "SUBJECT_MASTER_ID1_SEC_FLAG")
	private Integer SUBJECT_MASTER_ID1_SEC_FLAG;
	
	@Column(name = "SUBJECT_MASTER_ID1_EXP")
	private Integer SUBJECT_MASTER_ID1_EXP;
	
	@Column(name = "SUBJECT_MASTER_ID2")
	private String SUBJECT_MASTER_ID2;
	
	@Column(name = "SUBJECT_MASTER_ID2_PRM_FLAG")
	private Integer SUBJECT_MASTER_ID2_PRM_FLAG;
	
	@Column(name = "SUBJECT_MASTER_ID2_SEC_FLAG")
	private Integer SUBJECT_MASTER_ID2_SEC_FLAG;
	
	@Column(name = "SUBJECT_MASTER_ID2_EXP")
	private Integer SUBJECT_MASTER_ID2_EXP;
	
	@Column(name = "SUBJECT_MASTER_ID3")
	private String SUBJECT_MASTER_ID3;
	
	@Column(name = "SUBJECT_MASTER_ID3_PRM_FLAG")
	private Integer SUBJECT_MASTER_ID3_PRM_FLAG;
	
	@Column(name = "SUBJECT_MASTER_ID3_SEC_FLAG")
	private Integer SUBJECT_MASTER_ID3_SEC_FLAG;
	
	@Column(name = "SUBJECT_MASTER_ID3_EXP")
	private Integer SUBJECT_MASTER_ID3_EXP;
	
	@Column(name = "GENDER")
	private String GENDER;
	
	@Column(name = "BIRTH_YEAR")
	private Integer BIRTH_YEAR;
	
	@Column(name = "ADDR_STREET1")
	private String ADDR_STREET1;
	
	@Column(name = "ADDR_STREET2")
	private String ADDR_STREET2;
	
	@Column(name = "ADDR_CITY")
	private String ADDR_CITY;
	
	@Column(name = "ADDR_STATE_ID")
	private String ADDR_STATE_ID;

	@Column(name = "ADDR_ZIP")
	private String ADDR_ZIP;
	
	@Column(name = "REG_TEACHER_FLAG")
	private Integer REG_TEACHER_FLAG;
	
	@Column(name = "ASSISTANT_TEACHER_FLAG")
	private Integer ASSISTANT_TEACHER_FLAG;
	
	@Column(name = "EDU_UND_GRAD_COLLEGE")
	private String EDU_UND_GRAD_COLLEGE;
	
	@Column(name = "EDU_UND_GRAD_SUB_DEGREE")
	private String EDU_UND_GRAD_SUB_DEGREE;
	
	@Column(name = "EDU_UND_GRAD_HIGH_EDU_FLAG")
	private Integer EDU_UND_GRAD_HIGH_EDU_FLAG;
	
	@Column(name = "EDU_GRADUATION1_COLLEGE")
	private String EDU_GRADUATION1_COLLEGE;
	
	@Column(name = "EDU_GRADUATION1_SUB_DEGREE")
	private String EDU_GRADUATION1_SUB_DEGREE;
	
	@Column(name = "EDU_GRADUCATION1_HIGH_EDU_FLAG")
	private Integer EDU_GRADUCATION1_HIGH_EDU_FLAG;
	
	@Column(name = "EDU_GRADUATION2_COLLEGE")
	private String EDU_GRADUATION2_COLLEGE;
	
	@Column(name = "EDU_GRADUATION_SUB_DEGREE")
	private String EDU_GRADUATION_SUB_DEGREE;
	
	@Column(name = "EDU_GRADUCTION2_HIGH_EDU_FLAG")
	private Integer EDU_GRADUCTION2_HIGH_EDU_FLAG;
	
	@Column(name = "EDU_CERTIFIED_TEACHER_FLAG")
	private Integer EDU_CERTIFIED_TEACHER_FLAG;
	
	@Column(name = "EDU_CERTIFIED_TEACHER_DATE")
	private Date EDU_CERTIFIED_TEACHER_DATE;
	
	@Column(name = "SOURCE_ABOUT_US")
	private String SOURCE_ABOUT_US;
	
	@Column(name = "TERM_COND_ID1")
	private String TERM_COND_ID1;
	
	@Column(name = "TERM_COND_ID1_COMPLETION_DATE")
	private Date TERM_COND_ID1_COMPLETION_DATE;
	
	@Column(name = "TERM_COND_ID2")
	private String TERM_COND_ID2;
	
	@Column(name = "TERM_COND_ID2_COMPLETION_DATE")
	private Date TERM_COND_ID2_COMPLETION_DATE;
	
	@Column(name = "TERM_COND_ID3")
	private String TERM_COND_ID3;
	
	@Column(name = "TERM_COND_ID3_COMPLETION_DATE")
	private Date TERM_COND_ID3_COMPLETION_DATE;
	
	@Column(name = "TERM_COND_SIGNATURE")
	private String TERM_COND_SIGNATURE;
	
	@Column(name = "TERM_COND_SIGNATURE_DATE")
	private Date TERM_COND_SIGNATURE_DATE;
	
	@Column(name = "EMAIL_CONFIRMATION_COMPLETION_DATE")
	private Date EMAIL_CONFIRMATION_COMPLETION_DATE;
	
	@Column(name = "UPDATE_DATE")
	private Date UPDATE_DATE;

	public long getTEACHER_ID() {
		return TEACHER_ID;
	}

	public void setTEACHER_ID(long tEACHER_ID) {
		TEACHER_ID = tEACHER_ID;
	}

	public Integer getPROFILE_COMPLETE_FLAG() {
		return PROFILE_COMPLETE_FLAG;
	}

	public void setPROFILE_COMPLETE_FLAG(Integer pROFILE_COMPLETE_FLAG) {
		PROFILE_COMPLETE_FLAG = pROFILE_COMPLETE_FLAG;
	}

	public Date getPROFILE_COMPLETE_DATE() {
		return PROFILE_COMPLETE_DATE;
	}

	public void setPROFILE_COMPLETE_DATE(Date pROFILE_COMPLETE_DATE) {
		PROFILE_COMPLETE_DATE = pROFILE_COMPLETE_DATE;
	}

	public Integer getREG_SUBJECT_COMPLETE_FLAG() {
		return REG_SUBJECT_COMPLETE_FLAG;
	}

	public void setREG_SUBJECT_COMPLETE_FLAG(Integer rEG_SUBJECT_COMPLETE_FLAG) {
		REG_SUBJECT_COMPLETE_FLAG = rEG_SUBJECT_COMPLETE_FLAG;
	}

	public Integer getREG_AVAILABILITY_COMPLETE_FLAG() {
		return REG_AVAILABILITY_COMPLETE_FLAG;
	}

	public void setREG_AVAILABILITY_COMPLETE_FLAG(Integer rEG_AVAILABILITY_COMPLETE_FLAG) {
		REG_AVAILABILITY_COMPLETE_FLAG = rEG_AVAILABILITY_COMPLETE_FLAG;
	}

	public Integer getREG_BASICINFO1_COMPLETE_FLAG() {
		return REG_BASICINFO1_COMPLETE_FLAG;
	}

	public void setREG_BASICINFO1_COMPLETE_FLAG(Integer rEG_BASICINFO1_COMPLETE_FLAG) {
		REG_BASICINFO1_COMPLETE_FLAG = rEG_BASICINFO1_COMPLETE_FLAG;
	}

	public Integer getREG_BASICEDUCATION_COMPLETE_FLAG() {
		return REG_BASICEDUCATION_COMPLETE_FLAG;
	}

	public void setREG_BASICEDUCATION_COMPLETE_FLAG(Integer rEG_BASICEDUCATION_COMPLETE_FLAG) {
		REG_BASICEDUCATION_COMPLETE_FLAG = rEG_BASICEDUCATION_COMPLETE_FLAG;
	}

	public Integer getREG_PERSONAL_COMPLETE_FLAG() {
		return REG_PERSONAL_COMPLETE_FLAG;
	}

	public void setREG_PERSONAL_COMPLETE_FLAG(Integer rEG_PERSONAL_COMPLETE_FLAG) {
		REG_PERSONAL_COMPLETE_FLAG = rEG_PERSONAL_COMPLETE_FLAG;
	}

	public Integer getREG_TERMS1_COMPLETE_FLAG() {
		return REG_TERMS1_COMPLETE_FLAG;
	}

	public void setREG_TERMS1_COMPLETE_FLAG(Integer rEG_TERMS1_COMPLETE_FLAG) {
		REG_TERMS1_COMPLETE_FLAG = rEG_TERMS1_COMPLETE_FLAG;
	}

	public Integer getREG_TERMS2_COMPLETE_FLAG() {
		return REG_TERMS2_COMPLETE_FLAG;
	}

	public void setREG_TERMS2_COMPLETE_FLAG(Integer rEG_TERMS2_COMPLETE_FLAG) {
		REG_TERMS2_COMPLETE_FLAG = rEG_TERMS2_COMPLETE_FLAG;
	}

	public Integer getREG_CONF_ACK_COMPLETE_FLAG() {
		return REG_CONF_ACK_COMPLETE_FLAG;
	}

	public void setREG_CONF_ACK_COMPLETE_FLAG(Integer rEG_CONF_ACK_COMPLETE_FLAG) {
		REG_CONF_ACK_COMPLETE_FLAG = rEG_CONF_ACK_COMPLETE_FLAG;
	}

	public Integer getBACKGROUD_COMPLETE_FLAG() {
		return BACKGROUD_COMPLETE_FLAG;
	}

	public void setBACKGROUD_COMPLETE_FLAG(Integer bACKGROUD_COMPLETE_FLAG) {
		BACKGROUD_COMPLETE_FLAG = bACKGROUD_COMPLETE_FLAG;
	}

	public Date getBACKGROUD_COMPLETE_DATE() {
		return BACKGROUD_COMPLETE_DATE;
	}

	public void setBACKGROUD_COMPLETE_DATE(Date bACKGROUD_COMPLETE_DATE) {
		BACKGROUD_COMPLETE_DATE = bACKGROUD_COMPLETE_DATE;
	}

	public String getCLASS_ID1() {
		return CLASS_ID1;
	}

	public void setCLASS_ID1(String cLASS_ID1) {
		CLASS_ID1 = cLASS_ID1;
	}

	public String getCLASS_ID2() {
		return CLASS_ID2;
	}

	public void setCLASS_ID2(String cLASS_ID2) {
		CLASS_ID2 = cLASS_ID2;
	}

	public String getCLASS_ID3() {
		return CLASS_ID3;
	}

	public void setCLASS_ID3(String cLASS_ID3) {
		CLASS_ID3 = cLASS_ID3;
	}

	public Integer getCLASS_ALL_FLAG() {
		return CLASS_ALL_FLAG;
	}

	public void setCLASS_ALL_FLAG(Integer cLASS_ALL_FLAG) {
		CLASS_ALL_FLAG = cLASS_ALL_FLAG;
	}

	public String getSUBJECT_MASTER_ID1() {
		return SUBJECT_MASTER_ID1;
	}

	public void setSUBJECT_MASTER_ID1(String sUBJECT_MASTER_ID1) {
		SUBJECT_MASTER_ID1 = sUBJECT_MASTER_ID1;
	}

	public Integer getSUBJECT_MASTER_ID1_PRM_FLAG() {
		return SUBJECT_MASTER_ID1_PRM_FLAG;
	}

	public void setSUBJECT_MASTER_ID1_PRM_FLAG(Integer sUBJECT_MASTER_ID1_PRM_FLAG) {
		SUBJECT_MASTER_ID1_PRM_FLAG = sUBJECT_MASTER_ID1_PRM_FLAG;
	}

	public Integer getSUBJECT_MASTER_ID1_SEC_FLAG() {
		return SUBJECT_MASTER_ID1_SEC_FLAG;
	}

	public void setSUBJECT_MASTER_ID1_SEC_FLAG(Integer sUBJECT_MASTER_ID1_SEC_FLAG) {
		SUBJECT_MASTER_ID1_SEC_FLAG = sUBJECT_MASTER_ID1_SEC_FLAG;
	}

	public Integer getSUBJECT_MASTER_ID1_EXP() {
		return SUBJECT_MASTER_ID1_EXP;
	}

	public void setSUBJECT_MASTER_ID1_EXP(Integer sUBJECT_MASTER_ID1_EXP) {
		SUBJECT_MASTER_ID1_EXP = sUBJECT_MASTER_ID1_EXP;
	}

	public String getSUBJECT_MASTER_ID2() {
		return SUBJECT_MASTER_ID2;
	}

	public void setSUBJECT_MASTER_ID2(String sUBJECT_MASTER_ID2) {
		SUBJECT_MASTER_ID2 = sUBJECT_MASTER_ID2;
	}

	public Integer getSUBJECT_MASTER_ID2_PRM_FLAG() {
		return SUBJECT_MASTER_ID2_PRM_FLAG;
	}

	public void setSUBJECT_MASTER_ID2_PRM_FLAG(Integer sUBJECT_MASTER_ID2_PRM_FLAG) {
		SUBJECT_MASTER_ID2_PRM_FLAG = sUBJECT_MASTER_ID2_PRM_FLAG;
	}

	public Integer getSUBJECT_MASTER_ID2_SEC_FLAG() {
		return SUBJECT_MASTER_ID2_SEC_FLAG;
	}

	public void setSUBJECT_MASTER_ID2_SEC_FLAG(Integer sUBJECT_MASTER_ID2_SEC_FLAG) {
		SUBJECT_MASTER_ID2_SEC_FLAG = sUBJECT_MASTER_ID2_SEC_FLAG;
	}

	public Integer getSUBJECT_MASTER_ID2_EXP() {
		return SUBJECT_MASTER_ID2_EXP;
	}

	public void setSUBJECT_MASTER_ID2_EXP(Integer sUBJECT_MASTER_ID2_EXP) {
		SUBJECT_MASTER_ID2_EXP = sUBJECT_MASTER_ID2_EXP;
	}

	public String getSUBJECT_MASTER_ID3() {
		return SUBJECT_MASTER_ID3;
	}

	public void setSUBJECT_MASTER_ID3(String sUBJECT_MASTER_ID3) {
		SUBJECT_MASTER_ID3 = sUBJECT_MASTER_ID3;
	}

	public Integer getSUBJECT_MASTER_ID3_PRM_FLAG() {
		return SUBJECT_MASTER_ID3_PRM_FLAG;
	}

	public void setSUBJECT_MASTER_ID3_PRM_FLAG(Integer sUBJECT_MASTER_ID3_PRM_FLAG) {
		SUBJECT_MASTER_ID3_PRM_FLAG = sUBJECT_MASTER_ID3_PRM_FLAG;
	}

	public Integer getSUBJECT_MASTER_ID3_SEC_FLAG() {
		return SUBJECT_MASTER_ID3_SEC_FLAG;
	}

	public void setSUBJECT_MASTER_ID3_SEC_FLAG(Integer sUBJECT_MASTER_ID3_SEC_FLAG) {
		SUBJECT_MASTER_ID3_SEC_FLAG = sUBJECT_MASTER_ID3_SEC_FLAG;
	}

	public Integer getSUBJECT_MASTER_ID3_EXP() {
		return SUBJECT_MASTER_ID3_EXP;
	}

	public void setSUBJECT_MASTER_ID3_EXP(Integer sUBJECT_MASTER_ID3_EXP) {
		SUBJECT_MASTER_ID3_EXP = sUBJECT_MASTER_ID3_EXP;
	}

	public String getGENDER() {
		return GENDER;
	}

	public void setGENDER(String gENDER) {
		GENDER = gENDER;
	}

	public Integer getBIRTH_YEAR() {
		return BIRTH_YEAR;
	}

	public void setBIRTH_YEAR(Integer bIRTH_YEAR) {
		BIRTH_YEAR = bIRTH_YEAR;
	}

	public String getADDR_STREET1() {
		return ADDR_STREET1;
	}

	public void setADDR_STREET1(String aDDR_STREET1) {
		ADDR_STREET1 = aDDR_STREET1;
	}

	public String getADDR_STREET2() {
		return ADDR_STREET2;
	}

	public void setADDR_STREET2(String aDDR_STREET2) {
		ADDR_STREET2 = aDDR_STREET2;
	}

	public String getADDR_CITY() {
		return ADDR_CITY;
	}

	public void setADDR_CITY(String aDDR_CITY) {
		ADDR_CITY = aDDR_CITY;
	}

	public String getADDR_STATE_ID() {
		return ADDR_STATE_ID;
	}

	public void setADDR_STATE_ID(String aDDR_STATE_ID) {
		ADDR_STATE_ID = aDDR_STATE_ID;
	}

	public String getADDR_ZIP() {
		return ADDR_ZIP;
	}

	public void setADDR_ZIP(String aDDR_ZIP) {
		ADDR_ZIP = aDDR_ZIP;
	}

	public Integer getREG_TEACHER_FLAG() {
		return REG_TEACHER_FLAG;
	}

	public void setREG_TEACHER_FLAG(Integer rEG_TEACHER_FLAG) {
		REG_TEACHER_FLAG = rEG_TEACHER_FLAG;
	}

	public Integer getASSISTANT_TEACHER_FLAG() {
		return ASSISTANT_TEACHER_FLAG;
	}

	public void setASSISTANT_TEACHER_FLAG(Integer aSSISTANT_TEACHER_FLAG) {
		ASSISTANT_TEACHER_FLAG = aSSISTANT_TEACHER_FLAG;
	}

	public String getEDU_UND_GRAD_COLLEGE() {
		return EDU_UND_GRAD_COLLEGE;
	}

	public void setEDU_UND_GRAD_COLLEGE(String eDU_UND_GRAD_COLLEGE) {
		EDU_UND_GRAD_COLLEGE = eDU_UND_GRAD_COLLEGE;
	}

	public String getEDU_UND_GRAD_SUB_DEGREE() {
		return EDU_UND_GRAD_SUB_DEGREE;
	}

	public void setEDU_UND_GRAD_SUB_DEGREE(String eDU_UND_GRAD_SUB_DEGREE) {
		EDU_UND_GRAD_SUB_DEGREE = eDU_UND_GRAD_SUB_DEGREE;
	}

	public Integer getEDU_UND_GRAD_HIGH_EDU_FLAG() {
		return EDU_UND_GRAD_HIGH_EDU_FLAG;
	}

	public void setEDU_UND_GRAD_HIGH_EDU_FLAG(Integer eDU_UND_GRAD_HIGH_EDU_FLAG) {
		EDU_UND_GRAD_HIGH_EDU_FLAG = eDU_UND_GRAD_HIGH_EDU_FLAG;
	}

	public String getEDU_GRADUATION1_COLLEGE() {
		return EDU_GRADUATION1_COLLEGE;
	}

	public void setEDU_GRADUATION1_COLLEGE(String eDU_GRADUATION1_COLLEGE) {
		EDU_GRADUATION1_COLLEGE = eDU_GRADUATION1_COLLEGE;
	}

	public String getEDU_GRADUATION1_SUB_DEGREE() {
		return EDU_GRADUATION1_SUB_DEGREE;
	}

	public void setEDU_GRADUATION1_SUB_DEGREE(String eDU_GRADUATION1_SUB_DEGREE) {
		EDU_GRADUATION1_SUB_DEGREE = eDU_GRADUATION1_SUB_DEGREE;
	}

	public Integer getEDU_GRADUCATION1_HIGH_EDU_FLAG() {
		return EDU_GRADUCATION1_HIGH_EDU_FLAG;
	}

	public void setEDU_GRADUCATION1_HIGH_EDU_FLAG(Integer eDU_GRADUCATION1_HIGH_EDU_FLAG) {
		EDU_GRADUCATION1_HIGH_EDU_FLAG = eDU_GRADUCATION1_HIGH_EDU_FLAG;
	}

	public String getEDU_GRADUATION2_COLLEGE() {
		return EDU_GRADUATION2_COLLEGE;
	}

	public void setEDU_GRADUATION2_COLLEGE(String eDU_GRADUATION2_COLLEGE) {
		EDU_GRADUATION2_COLLEGE = eDU_GRADUATION2_COLLEGE;
	}

	public String getEDU_GRADUATION_SUB_DEGREE() {
		return EDU_GRADUATION_SUB_DEGREE;
	}

	public void setEDU_GRADUATION_SUB_DEGREE(String eDU_GRADUATION_SUB_DEGREE) {
		EDU_GRADUATION_SUB_DEGREE = eDU_GRADUATION_SUB_DEGREE;
	}

	public Integer getEDU_GRADUCTION2_HIGH_EDU_FLAG() {
		return EDU_GRADUCTION2_HIGH_EDU_FLAG;
	}

	public void setEDU_GRADUCTION2_HIGH_EDU_FLAG(Integer eDU_GRADUCTION2_HIGH_EDU_FLAG) {
		EDU_GRADUCTION2_HIGH_EDU_FLAG = eDU_GRADUCTION2_HIGH_EDU_FLAG;
	}

	public Integer getEDU_CERTIFIED_TEACHER_FLAG() {
		return EDU_CERTIFIED_TEACHER_FLAG;
	}

	public void setEDU_CERTIFIED_TEACHER_FLAG(Integer eDU_CERTIFIED_TEACHER_FLAG) {
		EDU_CERTIFIED_TEACHER_FLAG = eDU_CERTIFIED_TEACHER_FLAG;
	}

	public Date getEDU_CERTIFIED_TEACHER_DATE() {
		return EDU_CERTIFIED_TEACHER_DATE;
	}

	public void setEDU_CERTIFIED_TEACHER_DATE(Date eDU_CERTIFIED_TEACHER_DATE) {
		EDU_CERTIFIED_TEACHER_DATE = eDU_CERTIFIED_TEACHER_DATE;
	}

	public String getSOURCE_ABOUT_US() {
		return SOURCE_ABOUT_US;
	}

	public void setSOURCE_ABOUT_US(String sOURCE_ABOUT_US) {
		SOURCE_ABOUT_US = sOURCE_ABOUT_US;
	}

	public String getTERM_COND_ID1() {
		return TERM_COND_ID1;
	}

	public void setTERM_COND_ID1(String tERM_COND_ID1) {
		TERM_COND_ID1 = tERM_COND_ID1;
	}

	public Date getTERM_COND_ID1_COMPLETION_DATE() {
		return TERM_COND_ID1_COMPLETION_DATE;
	}

	public void setTERM_COND_ID1_COMPLETION_DATE(Date tERM_COND_ID1_COMPLETION_DATE) {
		TERM_COND_ID1_COMPLETION_DATE = tERM_COND_ID1_COMPLETION_DATE;
	}

	public String getTERM_COND_ID2() {
		return TERM_COND_ID2;
	}

	public void setTERM_COND_ID2(String tERM_COND_ID2) {
		TERM_COND_ID2 = tERM_COND_ID2;
	}

	public Date getTERM_COND_ID2_COMPLETION_DATE() {
		return TERM_COND_ID2_COMPLETION_DATE;
	}

	public void setTERM_COND_ID2_COMPLETION_DATE(Date tERM_COND_ID2_COMPLETION_DATE) {
		TERM_COND_ID2_COMPLETION_DATE = tERM_COND_ID2_COMPLETION_DATE;
	}

	public String getTERM_COND_ID3() {
		return TERM_COND_ID3;
	}

	public void setTERM_COND_ID3(String tERM_COND_ID3) {
		TERM_COND_ID3 = tERM_COND_ID3;
	}

	public Date getTERM_COND_ID3_COMPLETION_DATE() {
		return TERM_COND_ID3_COMPLETION_DATE;
	}

	public void setTERM_COND_ID3_COMPLETION_DATE(Date tERM_COND_ID3_COMPLETION_DATE) {
		TERM_COND_ID3_COMPLETION_DATE = tERM_COND_ID3_COMPLETION_DATE;
	}

	public String getTERM_COND_SIGNATURE() {
		return TERM_COND_SIGNATURE;
	}

	public void setTERM_COND_SIGNATURE(String tERM_COND_SIGNATURE) {
		TERM_COND_SIGNATURE = tERM_COND_SIGNATURE;
	}

	public Date getTERM_COND_SIGNATURE_DATE() {
		return TERM_COND_SIGNATURE_DATE;
	}

	public void setTERM_COND_SIGNATURE_DATE(Date tERM_COND_SIGNATURE_DATE) {
		TERM_COND_SIGNATURE_DATE = tERM_COND_SIGNATURE_DATE;
	}

	public Date getEMAIL_CONFIRMATION_COMPLETION_DATE() {
		return EMAIL_CONFIRMATION_COMPLETION_DATE;
	}

	public void setEMAIL_CONFIRMATION_COMPLETION_DATE(Date eMAIL_CONFIRMATION_COMPLETION_DATE) {
		EMAIL_CONFIRMATION_COMPLETION_DATE = eMAIL_CONFIRMATION_COMPLETION_DATE;
	}

	public Date getUPDATE_DATE() {
		return UPDATE_DATE;
	}

	public void setUPDATE_DATE(Date uPDATE_DATE) {
		UPDATE_DATE = uPDATE_DATE;
	}
	
	
}
